const readings = [
    ['Acorn', 'a long-term great success'],
    ['Aircraft', 'a long distance journey. If broken or pointing downward indicates an accident or trouble coming.'],
    ['Plane', 'a long distance journey. If broken or pointing downward indicates an accident or trouble coming.'],
    ['Helicopter', 'a long distance journey. If broken or pointing downward indicates an accident or trouble coming.'],
    ['Alligator', 'enemy waiting to hit, treachery.'],
    ['Reptile', 'enemy waiting to hit; treachery.'],
    ['Anchor', 'finding security in life.'],
    ['Angel', 'good news.'],
    ['Ant', 'success through perseverance.'],
    ['Apple', 'business achievement - if bitten represents a setback.'],
    ['Arch', 'happy event.'],
    ['Arrow', 'bad news.'],
    ['Axe', 'difficult situation has to be ended; decision has to be made.'],
    ['Baby', 'small worries.'],
    ['Bag', 'financially successful.'],
    ['Bagpipes', 'disappointment.'],
    ['Balloon', 'short-term troubles.'],
    ['Barrel', 'a party.'],
    ['Basin', 'trouble at home.'],
    ['Basket', 'if empty - money worries. If full - financial success. Surrounded by dots - money coming in.'],
    ['Bat', 'a journey ending in disappointment.'],
    ['Beans', 'poverty.'],
    ['Bear', 'decision made with strength and focus on success.'],
    ['Bed', 'stagnation.'],
    ['Bee', 'social success. Swarm of bees - success with an audience.'],
    ['Beehive', 'prosperity.'],
    ['Beetle', 'scandal, a difficult situation underway.'],
    ['Bell', 'unexpected news.'],
    ['Bird', 'money coming from an unknown source.'],
    ['Nest', 'domestic harmony, love.'],
    ['Bishop', 'good luck coming.'],
    ['Boat', 'journey over seas.'],
    ['Book', 'open - expect legal actions securing future success. Closed - delays and difficulties in achieving success.'],
    ['Boomerang', 'mall-intentions from others affecting you - protect yourself from bad words coming your way.'],
    ['Bottle', 'one bottle - pleasure. Several bottles - illness.'],
    ['Bouquet', 'love and happiness.'],
    ['Bow', 'bad news.'],
    ['Bowl', 'money flow or kind-heartedness'],
    ['Box', 'open - romantic troubles solved. Closed - the lost will be found.'],
    ['Bracelet', 'nearing marriage.'],
    ['Branch', 'with leaves - a satisfaction. Without leaves - a disappointment.'],
    ['Bread', 'avoid waste.'],
    ['Bridge', 'represents a way to cross the obstacles in opportunity for success.'],
    ['Broom', 'a false friend.'],
    ['Buckle', 'be wary, dangers ahead.'],
    ['Bugle', 'hard work necessary.'],
    ['Building', 'a change in location.'],
    ['Bull', 'quarrels, enmity.'],
    ['Bush', 'new fresh opportunities.'],
    ['Butterfly', 'freedom, happiness, worry-free'],
    ['Cabbage', 'jealousy causes complications at work.'],
    ['Cage', 'obstacles, quarrels.'],
    ['Camel', 'useful news exactly when needed.'],
    ['Cancer', 'the enemy.'],
    ['Candle', 'pursuit of knowledge-self improvement.'],
    ['Cannon', 'news of a soldier or a government employee.'],
    ['Cap', 'trouble ahead - be careful.'],
    ['Car', 'good fortune.'],
    ['Cart', 'success in business.'],
    ['Castle', 'financial gain through marriage.'],
    ['Cat', 'a false friend.'],
    ['Cattle', 'prosperity.'],
    ['Chain', 'engagement into venture with a partner or business partners.'],
    ['Chair', 'an unexpected guest.'],
    ['Cherries', 'a happy love affair.'],
    ['Chessmen', 'difficulties ahead.'],
    ['Chicken', 'domestic bliss.'],
    ['Chimney', 'hidden risks.'],
    ['Church', 'unexpected money, inheritance.'],
    ['Cigar', 'new friends.'],
    ['Circle', 'successful conclusion to venture.'],
    ['Circle with a dot', 'a baby, a new venture.'],
    ['Claw', 'a hidden enemy.'],
    ['Clock', 'it is time to think of the future.'],
    ['Clouds', 'trouble ahead.'],
    ['Clover', 'four leaf - you have luck on your side.'],
    ['Coat', 'a parting, an end to relationship or partnership.'],
    ['Cockatoo', 'mean gossip among friends.'],
    ['Coffeepot', 'illness.'],
    ['Coffin', 'bad news.'],
    ['Coin', 'debts will be paid.'],
    ['Column', 'promotion, upgrade, growth in your situation.'],
    ['Comb', 'organize your thoughts.'],
    ['Comet', 'an unexpected, surprise visitor.'],
    ['Compass', 'travel, a change of environment.'],
    ['Corkscrew', 'curiosity causing trouble.'],
    ['Crab', 'an enemy. (cancer)'],
    ['Crescent', 'love, relationship coming into your life.'],
    ['Crocodile', 'enemy waiting to hit, treachery.'],
    ['Cross', 'sacrifice, trouble.'],
    ['Crown', 'honour, success in a venture building a long time, wish coming true, a legacy.'],
    ['Crutches', 'help from a friend.'],
    ['Cup', 'reward for effort.'],
    ['Curtain', 'a secret.'],
    ['Daffodil', 'great happiness in life.'],
    ['Dagger', 'toxic situation needs to be ended.'],
    ['Daisy', 'happiness in love.'],
    ['Decrescent', 'keep your eyes opened, someone in your proximity loves you.'],
    ['Deer', 'a dispute or quarrel.'],
    ['Desk', 'social gathering, good venture.'],
    ['Devil', 'evil influences.'],
    ['Dish', 'quarrel at home.'],
    ['Dog', 'a good, loyal friend.'],
    ['Dolphin', 'good fortune in all things, health, wealth and happiness.'],
    ['Donkey', 'be patient and optimistic.'],
    ['Door', 'opportunity, opening to a new path.'],
    ['Dots', 'several black dots together means money in your future.'],
    ['Dove', 'good fortune.'],
    ['Dragon', 'desires fulfilled.'],
    ['Drum', 'scandal, gossip, arguments.'],
    ['Duck', 'money you are expecting is on the way in.'],
    ['Dustpan', 'strange news about a friend.'],
    ['Eagle', 'a big change for the better.'],
    ['Ear', 'unexpected news.'],
    ['Earrings', 'misunderstanding in what you hear.'],
    ['Egg', 'progress toward success.'],
    ['Elephant', 'wisdom, strength, lasting success built on firm foundation.'],
    ['Envelope', 'good news.'],
    ['Eye', 'be observant, watch for details. A mean eye - jealousy. Nice looking eye - someone is thinking about you.'],
    ['Face', 'one face - a change in belief of one area in life. Several faces - a change in lifestyle.'],
    ['Fairy', 'joy and enchantment.'],
    ['Fan', 'flirtation, indiscretion.'],
    ['Feather', 'instability, inconsistency, lack of concentration.'],
    ['Feet', 'an important decision.'],
    ['Fence', 'limitation to activities, minor setbacks toward future success.'],
    ['Fern', 'disloyalty, an unfaithful lover.'],
    ['Finger', 'emphasizes the symbol to which it points.'],
    ['Fir', 'artistic success. The higher the tree, the better.'],
    ['Fire', 'achievement, avoid hasty decisions.'],
    ['Fireplace', 'matters related to your home.'],
    ['Fish', 'good fortune in all things, health, wealth and happiness.'],
    ['Fist', 'an argument.'],
    ['Flag', 'danger ahead.'],
    ['Flower', 'wish coming true.'],
    ['Fly', 'domestic irritations. The more flies, the more annoying little problems.'],
    ['Fork', 'a deceitful friend.'],
    ['Forked line', 'many paths ahead, decision to be made.'],
    ['Fountain', 'future success and happiness.'],
    ['Fox', 'a deceitful friend, up to no good.'],
    ['Frog', 'success through a change of home or job-depending on the location in the grounds.'],
    ['Gallows', 'social failure.'],
    ['Garden roller', 'difficulties ahead.'],
    ['Garland', 'success, great honour.'],
    ['Gate', 'opportunity, opening to a new path.'],
    ['Geese', 'unexpected visitor.'],
    ['Giraffe', 'think before you speak.'],
    ['Glass', 'integrity.'],
    ['Glove', 'a challenge.'],
    ['Goat', 'enemies threaten.'],
    ['Gondola', 'romance, travel.'],
    ['Goose', 'finding good solutions.'],
    ['Gramophone', 'pleasure.'],
    ['Grapes', 'happiness.'],
    ['Grasshopper', 'news of a much travelled friend.'],
    ['Greyhound', 'good fortune, with help of loyal friend.'],
    ['Guitar', 'happiness in love.'],
    ['Gun', 'trouble, quarrels.'],
    ['Hammer', 'overcoming obstacles, ruthlessness, work that is uncongenial.'],
    ['Hand', 'friendship.'],
    ['Handcuffs', 'trouble ahead.'],
    ['Hare', 'timidity, tendency to pull away fast, be braver in a situation you are facing.'],
    ['Harp', 'harmony in love.'],
    ['Hat', 'a new occupation, a change in job. Bent and broken-likely to fail at this quest.'],
    ['Hawk', 'sudden danger born of jealousy.'],
    ['Hayrick', 'think before you act.'],
    ['Head', 'new opportunities.'],
    ['Heart', 'love and marriage.'],
    ['Heather flower', 'good fortune.'],
    ['Hen', 'domestic bliss.'],
    ['Hill', 'obstacles, setbacks.'],
    ['Hoe', 'hard work leading to success.'],
    ['Holly', 'an importance occurrence in the winter.'],
    ['Horn', 'be wary, dangers ahead.'],
    ['Horse', 'good news from a lover. Head only - romance.'],
    ['Horseshoe', 'good luck.'],
    ['House', 'security.'],
    ['Iceberg', 'danger.'],
    ['Initials', 'unusually those of people know to you. If next to a triangle, the initials of strangers.'],
    ['Inkpot', 'a letter.'],
    ['Insect', 'domestic irritations. The more flies, the more annoying little problems.'],
    ['Ivy leaf', 'reliable friend.'],
    ['Jester', 'party or social gathering-relaxing nature.'],
    ['Joker', 'party or social gathering-relaxing nature.'],
    ['Jewellery', 'a misunderstanding.'],
    ['Jug', 'gaining recognition, importance.'],
    ['Kangaroo', 'domestic harmony.'],
    ['Kettle', 'illness.'],
    ['Key', 'a new house, relocation, two keys crossed', ' success in investment.'],
    ['Keyhole', 'beware of curiosity of strangers.'],
    ['King', 'a powerful, successful ally.'],
    ['Kite', 'wishes coming true, keep an eye on it though, need to see it through.'],
    ['Knife', 'toxic situation needs to be ended.'],
    ['Ladder', 'promotion.'],
    ['Lamp', 'trouble threatening, but averted. Success through own knowledge.'],
    ['Leaf', 'prosperity, good fortune.'],
    ['Leo', 'influential friend.'],
    ['Leopard', 'news of a journey.'],
    ['Letter', 'good news. Near dots - news about money.'],
    ['Lighthouse', 'trouble threatening, but averted. Success through a friend.'],
    ['Lines', 'straight and clear - progress. Wavy - uncertainty. Slanting - failure.'],
    ['Lion', 'influential friends.'],
    ['Lock', 'obstacles in your path, if opened-obstacles overcame.'],
    ['Loop', 'impulsive actions could bring trouble.'],
    ['Man', 'a person relevant for the figures involved.'],
    ['Map', 'travel, change through travel.'],
    ['Mask', 'deception.'],
    ['Medal', 'a reward.'],
    ['Mermaid', 'temptation, an offer that is not what it seems.'],
    ['Mitre', 'honours.'],
    ['Monkey', 'a trickster.'],
    ['Monster', 'terror.'],
    ['Monument', 'lasting happiness.'],
    ['Moon', 'love, relationship coming into your life.'],
    ['Mountain', 'a high set ambition.'],
    ['Mouse', 'theft.'],
    ['Mushroom', 'fast moving growth.'],
    ['Music', 'good fortune.'],
    ['Nail', 'malice, injustice.'],
    ['Necklace', 'misunderstanding in what was done.'],
    ['Needle', 'be wary, minor dangers ahead.'],
    ['Net', 'traps for the unwary, be careful.'],
    ['Numbers', 'indicate a timeline, the number of days before events.'],
    ['Nun', 'quarantine.'],
    ['Nurse', 'illness or a trip to hospital.'],
    ['Nutcrackers', 'difficulty is passing.'],
    ['Oak', 'good fortune.'],
    ['Oar', 'a small worry, help from someone to overcome difficulties.'],
    ['Octopus', 'danger.'],
    ['Opera glasses', 'a quarrel, nitpicking.'],
    ['Ostrich', 'travel.'],
    ['Owl', 'gossip, scandal.'],
    ['Oyster', 'acquired riches.'],
    ['Paddle', 'a small worry, help from someone to overcome difficulties.'],
    ['Padlock', 'obstacles in your path, if opened-obstacles overcame.'],
    ['Palm tree', 'success, honour, happiness in love.'],
    ['Parachute', 'escape from danger.'],
    ['Parasol', 'a new lover.'],
    ['Parcel', 'a surprise.'],
    ['Parrot', 'mean gossip among friends.'],
    ['Peacock', 'with tail spread-riches. Surrounded by dots-luxurious life.'],
    ['Pear', 'comfort, financial ease.'],
    ['People', 'visitors.'],
    ['Pentagon', 'intellectual balance.'],
    ['Pepper shaker', 'a troublesome secret.'],
    ['Pig', 'material success brings emotional problems.'],
    ['Pegeon', 'an improvement in trade. Sitting-lasting improvement.'],
    ['Pillar', 'supportive friends or family members.'],
    ['Pine', 'an important event in winter.'],
    ['Pipe', 'keep an open mind, thinking to a solution.'],
    ['Pistol', 'trouble, quarrels.'],
    ['Pitchfork', 'a deceitful friend.'],
    ['Policeman', 'secret enemy.'],
    ['Pot', 'respect through service to society.'],
    ['Profile', 'a new friend.'],
    ['Pump', 'generosity.'],
    ['Purse', 'a profit.'],
    ['Pyramid', 'solid success.'],
    ['Question mark', 'hesitancy, caution.'],
    ['Rabbit', 'timidity, tendency to pull away fast, be braver in a situation you are facing. (hare)'],
    ['Railway', 'long journey.'],
    ['Rainbow', 'happiness, prosperity.'],
    ['Rake', 'organize your life.'],
    ['Rat', 'treachery.'],
    ['Raven', 'bad news.'],
    ['Razor', 'quarrels resulting in partings.'],
    ['Reptiles', 'enemy waiting to hit, treachery.'],
    ['Ribbon', 'happy event, celebration.'],
    ['Ring', 'the situation has come full circle-competition, two rings-marriage'],
    ['Rocks', 'burdens.'],
    ['Rod', 'visitor.'],
    ['Rose', 'popularity.'],
    ['Saw', 'person not connected to a situation interfering.'],
    ['Scales', 'a lawsuit. Balanced scales - justice. Unbalanced scales - injustice.'],
    ['Sceptre', 'power, authority.'],
    ['Scissors', 'domestic arguments.'],
    ['Scythe', 'be careful, someone could end your happiness.'],
    ['Shamrock', 'good luck, wish coming true.'],
    ['Sheep', 'happiness.'],
    ['Shell', 'acquired riches.'],
    ['Ship', 'successful journey.'],
    ['Shoe', 'a journey to a better situation.'],
    ['Sickle', 'e careful, someone could cause trouble in your happiness.'],
    ['Sign point', 'draws attention to the symbol to which it points.'],
    ['Skeleton', 'a sign of loosing hope in yourself, a need to build self up.'],
    ['Snake', 'hatred, an enemy set to destroy your world in a very sneaky way.'],
    ['Spade', 'hard work leads to success.'],
    ['Spider', 'determined and persistently accumulating, money coming in.'],
    ['Spoon', 'generosity.'],
    ['Square', 'a symbol of being protected.'],
    ['Squirrel', 'prosperity after a struggling time of work.'],
    ['Star', 'good health, happiness. Five-pointed star - good fortune.'],
    ['Steeple', 'slight delay in processing.'],
    ['Steps', 'an improvement in life.'],
    ['Stick', 'visitor.'],
    ['Sun', 'immense power, a very good and unexpected development.'],
    ['Swallow', 'journey.'],
    ['Swan', 'smooth progress, contented life.'],
    ['Sword', 'you are changing your life for better-fight for your happiness.'],
    ['Table', 'social gathering, good venture.'],
    ['Teapot', 'illness.'],
    ['Telephone', 'every truth has 3 sides to it, don’t jump to conclusions about what you hear.'],
    ['Telescope', 'adventure on your path.'],
    ['Tent', 'travel.'],
    ['Tie', 'happy event, celebration.'],
    ['Toad', 'beware of flattery, it can be deceiving.'],
    ['Torch', 'a turn for the better.'],
    ['Tortoise', 'criticism, keep a firm skin.'],
    ['Tower', 'financial growth in a slow and steady pace.'],
    ['Tree', 'things are evolving slowly but surely exactly as you want them to.'],
    ['Triangle', 'unexpected event. Point upward - brings success. Point downward - brings failure.'],
    ['Trident', 'a deceitful friend wielding the power.'],
    ['Trunk', 'a long journey, fateful decisions.'],
    ['Umbrella', 'annoyances, a need for shelter. If open - shelter found. If closed - shelter refused.'],
    ['Unicorn', 'the wish you were working to fulfill will be granted.'],
    ['Urn', 'wealth, happiness.'],
    ['Vase', 'a wedding celebration.'],
    ['Violin', 'selfishness.'],
    ['Volcano', 'emotions out of control-impatience.'],
    ['Vulture', 'your money is everywhere and you are going after it.'],
    ['Walking stick', 'a visitor.'],
    ['Wasp', 'trouble in love.'],
    ['Waterfall', 'prosperity.'],
    ['Weather vane', 'indecisiveness.'],
    ['Whale', 'good fortune in all things, health, wealth and happiness.'],
    ['Wheel', 'complete - earned success. Broken - disappointment.'],
    ['Wheelbarrow', 'a meeting with an old friend.'],
    ['Windmill', 'business success through hard work rather than brilliance.'],
    ['Window', 'open - good luck through a friend. Closed - disappointment through a friend.'],
    ['Wings', 'message.'],
    ['Wishbone', 'a wish granted.'],
    ['Wolf', 'inner strength, you will take care of self and yours.'],
    ['Woman', 'pleasure.'],
    ['Worms', 'scandal.'],
    ['Wreath', 'happiness ahead.'],
    ['Yacht', 'pleasure.'],
    ['Yoke', 'being dominated.'],
    ['Zebra', 'adventure overseas, an unsettled life.'],
    ['Zeppelin', 'delays, perseverance necessary.']
];